version: '3.5'
services:
  postgres:
    image: mdillon/postgis:9.2-alpine
    ports:
      - '5432:5432'
    networks:
      - nft_network
    #    volumes:
    #      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: nft_database
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nft_network:
    driver: bridge

volumes:
  gateway_data:
  postgres_data:
